### ISSUE TITLE
does not appear to work anymore

### ISSUE THREAD

**Issue by alfwro13** [noxiii/HANotifyNextCloudTalk#12]
I tested it in Home Assistant 2023.6.3 but got this error:

Platform error notify.nextcloudtalk - Integration 'nextcloudtalk' not found.
any chance this can be fixed? Or is that project is now dead?
Thanks

**Comment by noxiii** [comment]
Hey I use it at the moment with 2023.6.2 and it workd fine on my side. But after my last setup I must restart ha before I could configer the notify. I will test it later with 2023.6.3

I had no time to check the reason.

**Comment by alfwro13** [comment]
ok, sorry to have wasted your time - I manually created that folder, copied the files, restarted and now seems to work fine.
