### ISSUE TITLE
wrong indentation 

### ISSUE THREAD

**Issue by gabest11** [noxiii/HANotifyNextCloudTalk#18]
https://github.com/noxiii/HANotifyNextCloudTalk/blob/7ba4418befd7427a8cd40953cad73685e6cbeb86/nextcloudclient.py#L72

I think this else should be in line with "if resp.status_code == 201:"

**Comment by noxiii** [comment]
thank you. I changed it with:
https://github.com/noxiii/HANotifyNextCloudTalk/pull/20
